### ISSUE TITLE
Crash with small density.rgb values

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#159]
Came across a scene that was having trouble with density.rgb values very close to 0.

NaNs and Infs started having a party in 
https://github.com/mmp/pbrt-v4/blob/8d12d6658d8b37a05b1ee6571aa75e010f392ae1/src/pbrt/util/color.cpp#L36-L73
```
0x0000000000a4b428 in pbrt::RGBToSpectrumTable::operator() (this=0x8cd1e00, rgb=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/util/color.cpp:66
66              c[j] = ((data[offset] * x0 + data[offset + dx] * x1) * y0 +
(gdb) bt
#0  0x0000000000a4b428 in pbrt::RGBToSpectrumTable::operator() (this=0x8cd1e00, rgb=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/util/color.cpp:66
#1  0x0000000000a51c91 in pbrt::RGBColorSpace::ToRGBCoeffs (this=0x8cc60f0, rgb=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/util/colorspace.cpp:48
#2  0x0000000000b17bff in pbrt::RGBUnboundedSpectrum::RGBUnboundedSpectrum (this=0x7fffee7379c8, cs=..., rgb=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/util/spectrum.cpp:243
#3  0x0000000000cf40d5 in pbrt::UniformGridMediumProvider::Create (parameters=..., loc=0x8ce2530, alloc=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/media.cpp:281
#4  0x0000000000cf5c13 in pbrt::Medium::Create (name="uniformgrid", parameters=..., renderFromMedium=..., loc=0x8ce2530, alloc=...) at /home/shadeops/repos/pbrt-v4/src/pbrt/media.cpp:391
#5  0x00000000009167f5 in pbrt::ParsedScene::AddMedium(pbrt::TransformedSceneEntity)::$_6::operator()() const (this=0x8ce2510) at /home/shadeops/repos/pbrt-v4/src/pbrt/scene.cpp:833
```

```
(gdb) info locals
j = 0
i = 2
z = 9.99999991e-38
sc = inf
x = -nan(0x400000)
y = -nan(0x400000)
nCoeffs = 3
xi = -2147483648
yi = -2147483648
zi = 0
offset = -2145910784
dx = 3
dy = 192
dz = 12288
x1 = -nan(0x400000)
x0 = -nan(0x400000)
y1 = -nan(0x400000)
y0 = -nan(0x400000)
z1 = 5.96287083e-32
z0 = 1
c = {values = {0, 0, 0}}
```

```
Film "rgb"
    "string filename" [ "pbrt.exr" ]
    "integer yresolution" [ 512 ]
    "integer xresolution" [ 512 ]
PixelFilter "gaussian"
    "float xradius" [ 2 ]
    "float yradius" [ 2 ]
Sampler "zsobol"
    "integer pixelsamples" [ 16 ]
Integrator "volpath"
    "integer maxdepth" [ 5 ]
#  /obj/cam1
Accelerator "bvh"
Transform [ 1 0 0 0 0 1 0 0 0 0 -1 0 0 0 5 1  ]
Camera "perspective"
    "float screenwindow" [ -1 1 -0.5625 0.5625 ]
    "float fov" [ 45 ]


WorldBegin

AttributeBegin
    # {
    Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1  ]
    Scale 1 1 -1
    Rotate 90 0 0 1
    Rotate 90 0 1 0
    LightSource "infinite"
        "float scale" [ 1 ]
AttributeEnd

AttributeBegin
    ConcatTransform [ 0.5 0 0 0 0 0.5 0 0 0 0 0.5 0 0 0 0 1  ]
    MakeNamedMedium "/obj/geo1/volume1[0,1,2]"
        "spectrum sigma_s" [ 400 1 800 1 ]
        "point3 p1" [ 1 1 1 ]
        "point3 p0" [ -1 -1 -1 ]
        "spectrum sigma_a" [ 400 0 800 0 ]
        "rgb density.rgb" [ 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 
                            0 0 1e-37 0 0 1e-37 0 0 1e-37 0 0 1e-37 ]
        "integer nz" [ 4 ]
        "integer ny" [ 4 ]
        "integer nx" [ 4 ]
        "string type" [ "uniformgrid" ]

    Material "interface"
    MediumInterface "/obj/geo1/volume1[0,1,2]" ""
    Shape "trianglemesh"
        "point3 P" [ 1 -1 1 -1 -1 1 1 1 1 -1 1 1 -1 -1 -1 1 -1 -1 -1 1 -1 1 1 
                     -1 ]
        "integer indices" [ 0 3 1 0 2 3 4 7 5 4 6 7 6 2 7 6 3 2 5 1 4 5 0 1 5 
                            2 0 5 7 2 1 6 4 1 3 6 ]
AttributeEnd
```

Easily worked around on the DCC side with something like `density = density < 0.0001 ? 0 : density` but figured it was worth flagging. :)

**Comment by shadeops** [comment]
Complementary imagery -

https://user-images.githubusercontent.com/2104033/128068565-38c5f53a-07c8-4cc1-bea7-9a9c30643272.mp4

**Comment by mmp** [comment]
Nice animation!!

That was an interesting and obscure failure, but good to have it fixed (I think) now. Let me know if this takes care of it on your side (it seems to do it for the test case.)
