### ISSUE TITLE
CUDATrackedMemoryResource crash when rendering with wavefront

### ISSUE THREAD

**Issue by shadeops** [mmp/pbrt-v4#170]
# Overview

Howdy!

I have a simple scene that is crashing with recent builds of pbrt when rendering with `--wavefront`. Running a git bisect reports that https://github.com/mmp/pbrt-v4/commit/f74d7da8f588687179df63d9bc5ec48e3a95151f seems to have introduced the issue. Interestingly `--gpu` runs fine with the same scene. (Hopefully not another CPU nvcc bug)

Here is a backtrace compiled with f74d7da

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5f7d859 in __GI_abort () at abort.c:79
#2  0x0000555555f02e52 in pbrt::CheckCallbackScope::Fail () at /pbrt-v4/src/pbrt/util/check.cpp:158
#3  0x0000555555c86b28 in pbrt::LogFatal (level=pbrt::LogLevel::Fatal, file=0x55555890e6d8 "/pbrt-v4/src/pbrt/wavefront/integrator.cpp", line=320, s=0x55555da61df0 "Check failed: mr") at /pbrt-v4/src/pbrt/util/log.cpp:319
#4  0x0000555555e22b59 in pbrt::LogFatal<char const (&) [3]> (level=pbrt::LogLevel::Fatal, file=0x55555890e6d8 "/pbrt-v4/src/pbrt/wavefront/integrator.cpp", line=320, fmt=0x55555890dde4 "Check failed: %s") at /pbrt-v4/src/pbrt/util/log.h:117
#5  0x0000555555f36b12 in pbrt::WavefrontPathIntegrator::WavefrontPathIntegrator (this=0x55555da60d60, memoryResource=0x55555cf28058 <pstd::pmr::ndr>, scene=...) at /pbrt-v4/src/pbrt/wavefront/integrator.cpp:320
#6  0x0000555555d4abe6 in pbrt::RenderWavefront (scene=...) at /pbrt-v4/src/pbrt/wavefront/wavefront.cpp:36
#7  0x0000555555a0d670 in main (argc=7, argv=0x7fffffffdb88) at /pbrt-v4/src/pbrt/cmd/pbrt.cpp:259
```

When compiled with b40ea10 it crashes here -
https://github.com/mmp/pbrt-v4/blob/b40ea1022ca92ee89c7a36e2ea7aa31c3497285c/src/pbrt/wavefront/integrator.cpp#L237-L239

# Example Scene
```
Film "rgb"
    "string filename" [ "boom.exr" ]
    "integer yresolution" [ 270 ]
    "integer xresolution" [ 480 ]

Sampler "zsobol"
    "integer pixelsamples" [ 16 ]

Integrator "volpath"
    "integer maxdepth" [ 5 ]

Accelerator "bvh"
Transform [ 1 0 0 0 0 1 0 0 0 0 -1 0 0 -1.1793004 6.285956 1  ]

Camera "perspective"
    "float screenwindow" [ -1 1 -0.5625 0.5625 ]
    "float fov" [ 45. ]

WorldBegin

AttributeBegin
    # {
    Transform [ 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1  ]
    Scale 1 1 -1
    Rotate 90 0 0 1
    Rotate 90 0 1 0
    LightSource "infinite"
        "float scale" [ 1 ]
AttributeEnd

MakeNamedMaterial "/mat/pbrt_material_coateddiffuse1"
    "string type" [ "coateddiffuse" ]

AttributeBegin
    ConcatTransform [ 5 0 0 0 0 5 0 0 0 0 5 0 0 0 0 1  ]
    NamedMaterial "/mat/pbrt_material_coateddiffuse1"
    Shape "trianglemesh"
        "normal N" [ 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 ]
        "point2 uv" [ 0 0 1 0 1 1 1 1 0 1 0 0 ]
        "point3 P" [ -5 0 -5 5 0 -5 5 0 5 5 0 5 -5 0 5 -5 0 -5 ]
        "integer indices" [ 0 1 2 3 4 5 ]
AttributeEnd
```
Rendered with 
```
pbrt --nthreads 1 --wavefront --display-server localhost:14158 boom.pbrt 
```

# Specs
* Ubuntu 20.04
* Nvidia GTX 3080
* Nvidia Optix 7.2
* gcc 9.3.0
* Tested with nvcc 11.2.142 & nvcc 11.4.100
* Tested commits b40ea10 & f74d7da

**Comment by shadeops** [comment]
render tax -

![matchbulb_50](https://user-images.githubusercontent.com/2104033/129855481-355a8556-5a6d-4c32-989d-6bd015ef252c.png)

(Ignore the few black pixels, I'm in the process of debugging some NaNs that show up in GPU rendering but not with the standard VolPath. Hence why trying to get --wavefront happy again. :grin: )

**Comment by mmp** [comment]
Nice image! No doubt a fine proof of why pbrt should sample volumetric emitters better :-)

This should be fixed now. The CPU wavefront integrator path deserves more testing attention so I'll do that now to see if anything else pops up.
